-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:b5a7afe75e8a861f8c3a977366f4bc7f$
-- 

return {
	texture = 'Objects.tex',
	frames = {
			{
				name = "AirScrubber",
				spriteColorRect = { x = 16, y = 68, width = 94, height = 112 },
				uvRect = { u0 = 0.952148, v0 = 0.522461, u1 = 0.998047, v1 = 0.577148 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AirScrubber_damaged",
				spriteColorRect = { x = 0, y = 68, width = 122, height = 112 },
				uvRect = { u0 = 0.80127, v0 = 0.852539, u1 = 0.86084, v1 = 0.907227 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AirScrubber_destroyed",
				spriteColorRect = { x = 0, y = 68, width = 124, height = 112 },
				uvRect = { u0 = 0.344727, v0 = 0.588379, u1 = 0.399414, v1 = 0.648926 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "DutyLocker",
				spriteColorRect = { x = 3, y = 108, width = 102, height = 148 },
				uvRect = { u0 = 0.948242, v0 = 0.726562, u1 = 0.998047, v1 = 0.798828 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Env_Datacube",
				spriteColorRect = { x = 102, y = 90, width = 58, height = 104 },
				uvRect = { u0 = 0.102539, v0 = 0.656738, u1 = 0.15332, v1 = 0.685059 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "ShelvesWallStack",
				spriteColorRect = { x = 0, y = 68, width = 74, height = 120 },
				uvRect = { u0 = 0.365234, v0 = 0.252441, u1 = 0.401367, v1 = 0.311035 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ShipEngine",
				spriteColorRect = { x = 22, y = 1, width = 208, height = 246 },
				uvRect = { u0 = 0.124023, v0 = 0.252441, u1 = 0.244141, v1 = 0.354004 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffAlarmClock",
				spriteColorRect = { x = 106, y = 166, width = 44, height = 30 },
				uvRect = { u0 = 0.228516, v0 = 0.834473, u1 = 0.243164, v1 = 0.855957 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffBaseball",
				spriteColorRect = { x = 120, y = 175, width = 16, height = 14 },
				uvRect = { u0 = 0.233398, v0 = 0.487793, u1 = 0.240234, v1 = 0.495605 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffBasketball",
				spriteColorRect = { x = 109, y = 165, width = 36, height = 28 },
				uvRect = { u0 = 0.782227, v0 = 0.756836, u1 = 0.799805, v1 = 0.770508 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffCandyBucket",
				spriteColorRect = { x = 106, y = 166, width = 42, height = 28 },
				uvRect = { u0 = 0.136719, v0 = 0.90918, u1 = 0.150391, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffCowSkull",
				spriteColorRect = { x = 101, y = 161, width = 54, height = 38 },
				uvRect = { u0 = 0.00195312, v0 = 0.766113, u1 = 0.0205078, v1 = 0.79248 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffDeadEarthGlobe",
				spriteColorRect = { x = 97, y = 147, width = 58, height = 52 },
				uvRect = { u0 = 0.842773, v0 = 0.391113, u1 = 0.868164, v1 = 0.419434 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffDucky",
				spriteColorRect = { x = 113, y = 170, width = 32, height = 24 },
				uvRect = { u0 = 0.640625, v0 = 0.296387, u1 = 0.652344, v1 = 0.312012 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffEarthGlobe",
				spriteColorRect = { x = 97, y = 149, width = 58, height = 50 },
				uvRect = { u0 = 0.078125, v0 = 0.834473, u1 = 0.106445, v1 = 0.858887 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffGnome",
				spriteColorRect = { x = 110, y = 161, width = 34, height = 32 },
				uvRect = { u0 = 0.137695, v0 = 0.859863, u1 = 0.15332, v1 = 0.876465 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffGnome_tint",
				spriteColorRect = { x = 114, y = 147, width = 20, height = 18 },
				uvRect = { u0 = 0.640625, v0 = 0.324707, u1 = 0.650391, v1 = 0.333496 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffHumanSkull",
				spriteColorRect = { x = 102, y = 152, width = 48, height = 44 },
				uvRect = { u0 = 0.131836, v0 = 0.834473, u1 = 0.15332, v1 = 0.85791 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffKitty",
				spriteColorRect = { x = 103, y = 157, width = 46, height = 36 },
				uvRect = { u0 = 0.614258, v0 = 0.533691, u1 = 0.636719, v1 = 0.55127 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffKitty_tint",
				spriteColorRect = { x = 105, y = 156, width = 36, height = 32 },
				uvRect = { u0 = 0.814453, v0 = 0.527344, u1 = 0.832031, v1 = 0.542969 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffLavalamp",
				spriteColorRect = { x = 115, y = 145, width = 26, height = 46 },
				uvRect = { u0 = 0.933594, v0 = 0.787598, u1 = 0.946289, v1 = 0.810059 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffLittleCactus",
				spriteColorRect = { x = 104, y = 154, width = 44, height = 40 },
				uvRect = { u0 = 0.780273, v0 = 0.801758, u1 = 0.799805, v1 = 0.823242 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffMoaiHead",
				spriteColorRect = { x = 108, y = 153, width = 40, height = 42 },
				uvRect = { u0 = 0.0810547, v0 = 0.90918, u1 = 0.100586, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffModelSpacebus",
				spriteColorRect = { x = 115, y = 168, width = 32, height = 26 },
				uvRect = { u0 = 0.933594, v0 = 0.83252, u1 = 0.946289, v1 = 0.848145 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffMug",
				spriteColorRect = { x = 106, y = 162, width = 42, height = 32 },
				uvRect = { u0 = 0.102539, v0 = 0.90918, u1 = 0.118164, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffMug_tint",
				spriteColorRect = { x = 118, y = 168, width = 24, height = 18 },
				uvRect = { u0 = 0.640625, v0 = 0.313965, u1 = 0.652344, v1 = 0.322754 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffMusicBox",
				spriteColorRect = { x = 104, y = 158, width = 44, height = 36 },
				uvRect = { u0 = 0.782227, v0 = 0.695312, u1 = 0.799805, v1 = 0.716797 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffOldComputer",
				spriteColorRect = { x = 89, y = 145, width = 76, height = 56 },
				uvRect = { u0 = 0.00195312, v0 = 0.960449, u1 = 0.0292969, v1 = 0.997559 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffPictureFrame01",
				spriteColorRect = { x = 96, y = 151, width = 64, height = 50 },
				uvRect = { u0 = 0.842773, v0 = 0.440918, u1 = 0.867188, v1 = 0.472168 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffPictureFrame02",
				spriteColorRect = { x = 98, y = 154, width = 56, height = 44 },
				uvRect = { u0 = 0.924316, v0 = 0.931152, u1 = 0.945801, v1 = 0.958496 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffPictureFrame03",
				spriteColorRect = { x = 98, y = 154, width = 56, height = 44 },
				uvRect = { u0 = 0.924316, v0 = 0.901855, u1 = 0.945801, v1 = 0.929199 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffPocketWatch",
				spriteColorRect = { x = 108, y = 176, width = 34, height = 16 },
				uvRect = { u0 = 0.219727, v0 = 0.627441, u1 = 0.227539, v1 = 0.644043 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffPuzzleCube",
				spriteColorRect = { x = 102, y = 162, width = 52, height = 36 },
				uvRect = { u0 = 0.842773, v0 = 0.421387, u1 = 0.868164, v1 = 0.438965 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffRadio",
				spriteColorRect = { x = 98, y = 154, width = 60, height = 46 },
				uvRect = { u0 = 0.614258, v0 = 0.473145, u1 = 0.636719, v1 = 0.502441 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffTeddyBear",
				spriteColorRect = { x = 101, y = 154, width = 56, height = 46 },
				uvRect = { u0 = 0.614258, v0 = 0.504395, u1 = 0.636719, v1 = 0.531738 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffTeddyBear_tint",
				spriteColorRect = { x = 110, y = 153, width = 36, height = 40 },
				uvRect = { u0 = 0.782227, v0 = 0.71875, u1 = 0.799805, v1 = 0.738281 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffTentacleMonster",
				spriteColorRect = { x = 98, y = 154, width = 60, height = 50 },
				uvRect = { u0 = 0.046875, v0 = 0.834473, u1 = 0.0761719, v1 = 0.858887 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffToyBall",
				spriteColorRect = { x = 103, y = 175, width = 46, height = 20 },
				uvRect = { u0 = 0.219727, v0 = 0.57959, u1 = 0.229492, v1 = 0.602051 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "StuffToyBall_tint",
				spriteColorRect = { x = 114, y = 159, width = 28, height = 28 },
				uvRect = { u0 = 0.185547, v0 = 0.827148, u1 = 0.199219, v1 = 0.84082 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffToyParasite",
				spriteColorRect = { x = 107, y = 152, width = 42, height = 42 },
				uvRect = { u0 = 0.0585938, v0 = 0.90918, u1 = 0.0791016, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffToySpacelady",
				spriteColorRect = { x = 112, y = 152, width = 38, height = 40 },
				uvRect = { u0 = 0.152344, v0 = 0.90918, u1 = 0.170898, v1 = 0.928711 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffToySpaceman",
				spriteColorRect = { x = 112, y = 151, width = 30, height = 40 },
				uvRect = { u0 = 0.172852, v0 = 0.90918, u1 = 0.1875, v1 = 0.928711 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffToyWizard",
				spriteColorRect = { x = 117, y = 145, width = 18, height = 44 },
				uvRect = { u0 = 0.219727, v0 = 0.604004, u1 = 0.228516, v1 = 0.625488 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "StuffTrilobiteFossil",
				spriteColorRect = { x = 93, y = 159, width = 76, height = 48 },
				uvRect = { u0 = 0.0820312, v0 = 0.960449, u1 = 0.105469, v1 = 0.997559 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Trash01",
				spriteColorRect = { x = 89, y = 164, width = 58, height = 34 },
				uvRect = { u0 = 0.155273, v0 = 0.827148, u1 = 0.183594, v1 = 0.84375 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Trash02",
				spriteColorRect = { x = 100, y = 177, width = 32, height = 14 },
				uvRect = { u0 = 0.233398, v0 = 0.470215, u1 = 0.240234, v1 = 0.48584 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Trash03",
				spriteColorRect = { x = 92, y = 164, width = 56, height = 30 },
				uvRect = { u0 = 0.137695, v0 = 0.878418, u1 = 0.152344, v1 = 0.905762 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Trash04",
				spriteColorRect = { x = 100, y = 168, width = 42, height = 30 },
				uvRect = { u0 = 0.120117, v0 = 0.90918, u1 = 0.134766, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "Trash05",
				spriteColorRect = { x = 93, y = 162, width = 50, height = 42 },
				uvRect = { u0 = 0.0322266, v0 = 0.90918, u1 = 0.0566406, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "airlock_locker",
				spriteColorRect = { x = 0, y = 10, width = 102, height = 174 },
				uvRect = { u0 = 0.727539, v0 = 0.527344, u1 = 0.8125, v1 = 0.577148 },
				spriteSourceSize = { width = 128, height = 196 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "airlock_locker_damaged",
				spriteColorRect = { x = 0, y = 10, width = 102, height = 174 },
				uvRect = { u0 = 0.517578, v0 = 0.54834, u1 = 0.602539, v1 = 0.598145 },
				spriteSourceSize = { width = 128, height = 196 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "airlock_locker_destroyed",
				spriteColorRect = { x = 0, y = 9, width = 112, height = 182 },
				uvRect = { u0 = 0.654297, v0 = 0.283691, u1 = 0.743164, v1 = 0.338379 },
				spriteSourceSize = { width = 128, height = 196 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "alarm_panel",
				spriteColorRect = { x = 13, y = 0, width = 38, height = 102 },
				uvRect = { u0 = 0.927734, v0 = 0.850098, u1 = 0.946289, v1 = 0.899902 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "alarm_panel_on",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 102 },
				uvRect = { u0 = 0.948242, v0 = 0.842773, u1 = 0.998047, v1 = 0.882812 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "alarm_panel_on_flip",
				spriteColorRect = { x = 56, y = 0, width = 82, height = 102 },
				uvRect = { u0 = 0.948242, v0 = 0.800781, u1 = 0.998047, v1 = 0.84082 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "bar",
				spriteColorRect = { x = 19, y = 133, width = 164, height = 140 },
				uvRect = { u0 = 0.870117, v0 = 0.419434, u1 = 0.950195, v1 = 0.487793 },
				spriteSourceSize = { width = 192, height = 280 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "bed",
				spriteColorRect = { x = 0, y = 4, width = 195, height = 123 },
				uvRect = { u0 = 0.736816, v0 = 0.465332, u1 = 0.832031, v1 = 0.525391 },
				spriteSourceSize = { width = 205, height = 127 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "breach_drill",
				spriteColorRect = { x = 0, y = 114, width = 128, height = 142 },
				uvRect = { u0 = 0.710938, v0 = 0.695312, u1 = 0.780273, v1 = 0.757812 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "breach_ladder",
				spriteColorRect = { x = 7, y = 138, width = 114, height = 94 },
				uvRect = { u0 = 0.952148, v0 = 0.464844, u1 = 0.998047, v1 = 0.520508 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "dec_greeble01",
				spriteColorRect = { x = 11, y = 0, width = 102, height = 99 },
				uvRect = { u0 = 0.586914, v0 = 0.744629, u1 = 0.636719, v1 = 0.792969 },
				spriteSourceSize = { width = 124, height = 99 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dec_wall_neon_burger",
				spriteColorRect = { x = 2, y = 43, width = 38, height = 38 },
				uvRect = { u0 = 0.0224609, v0 = 0.766113, u1 = 0.0410156, v1 = 0.784668 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dec_wall_neon_fries",
				spriteColorRect = { x = 1, y = 27, width = 44, height = 66 },
				uvRect = { u0 = 0.604492, v0 = 0.589355, u1 = 0.636719, v1 = 0.61084 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "dec_wall_neon_pizza",
				spriteColorRect = { x = 2, y = 33, width = 44, height = 48 },
				uvRect = { u0 = 0.108398, v0 = 0.834473, u1 = 0.129883, v1 = 0.85791 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "dockpoint",
				spriteColorRect = { x = 28, y = 13, width = 72, height = 40 },
				uvRect = { u0 = 0.480469, v0 = 0.560059, u1 = 0.515625, v1 = 0.57959 },
				spriteSourceSize = { width = 128, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fire_panel",
				spriteColorRect = { x = 0, y = 9, width = 54, height = 104 },
				uvRect = { u0 = 0.00195312, v0 = 0.932129, u1 = 0.0527344, v1 = 0.958496 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "food01",
				spriteColorRect = { x = 45, y = 151, width = 38, height = 26 },
				uvRect = { u0 = 0.933594, v0 = 0.812012, u1 = 0.946289, v1 = 0.830566 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "food_replicator",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 154 },
				uvRect = { u0 = 0.516602, v0 = 0.600098, u1 = 0.591797, v1 = 0.646973 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "food_replicator_damaged",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 154 },
				uvRect = { u0 = 0.401367, v0 = 0.609863, u1 = 0.476562, v1 = 0.656738 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "food_replicator_destroyed",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 154 },
				uvRect = { u0 = 0.951172, v0 = 0.579102, u1 = 0.998047, v1 = 0.654297 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fridge",
				spriteColorRect = { x = 18, y = 100, width = 92, height = 156 },
				uvRect = { u0 = 0.953125, v0 = 0.320312, u1 = 0.998047, v1 = 0.396484 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fridge_damaged",
				spriteColorRect = { x = 18, y = 100, width = 96, height = 156 },
				uvRect = { u0 = 0.353516, v0 = 0.510254, u1 = 0.400391, v1 = 0.586426 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fridge_destroyed",
				spriteColorRect = { x = 17, y = 100, width = 98, height = 156 },
				uvRect = { u0 = 0.402344, v0 = 0.560059, u1 = 0.478516, v1 = 0.60791 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "fridge_level2",
				spriteColorRect = { x = 8, y = 100, width = 106, height = 156 },
				uvRect = { u0 = 0.870117, v0 = 0.733887, u1 = 0.946289, v1 = 0.785645 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "fridge_level2_damaged",
				spriteColorRect = { x = 6, y = 100, width = 110, height = 156 },
				uvRect = { u0 = 0.870117, v0 = 0.678223, u1 = 0.946289, v1 = 0.731934 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "fridge_level2_destroyed",
				spriteColorRect = { x = 6, y = 100, width = 110, height = 156 },
				uvRect = { u0 = 0.723633, v0 = 0.639648, u1 = 0.799805, v1 = 0.693359 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "fridge_level2_open",
				spriteColorRect = { x = 8, y = 100, width = 120, height = 156 },
				uvRect = { u0 = 0.723633, v0 = 0.579102, u1 = 0.799805, v1 = 0.637695 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "fridge_open",
				spriteColorRect = { x = 18, y = 100, width = 110, height = 156 },
				uvRect = { u0 = 0.814453, v0 = 0.54541, u1 = 0.868164, v1 = 0.621582 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator",
				spriteColorRect = { x = 16, y = 0, width = 208, height = 238 },
				uvRect = { u0 = 0.522461, v0 = 0.296387, u1 = 0.638672, v1 = 0.397949 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "generator2",
				spriteColorRect = { x = 2, y = 25, width = 252, height = 222 },
				uvRect = { u0 = 0.529297, v0 = 0.186035, u1 = 0.652344, v1 = 0.294434 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator2_damaged",
				spriteColorRect = { x = 2, y = 25, width = 254, height = 222 },
				uvRect = { u0 = 0.40332, v0 = 0.186035, u1 = 0.527344, v1 = 0.294434 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator2_destroyed",
				spriteColorRect = { x = 3, y = 32, width = 252, height = 214 },
				uvRect = { u0 = 0.745117, v0 = 0.284668, u1 = 0.868164, v1 = 0.38916 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "generator_damaged",
				spriteColorRect = { x = 15, y = 0, width = 230, height = 238 },
				uvRect = { u0 = 0.00195312, v0 = 0.366699, u1 = 0.118164, v1 = 0.479004 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "generator_destroyed",
				spriteColorRect = { x = 10, y = 0, width = 230, height = 238 },
				uvRect = { u0 = 0.124023, v0 = 0.355957, u1 = 0.240234, v1 = 0.468262 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "hospital_bed",
				spriteColorRect = { x = 2, y = 83, width = 222, height = 166 },
				uvRect = { u0 = 0.870117, v0 = 0.309082, u1 = 0.951172, v1 = 0.41748 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "hospital_bed_damaged",
				spriteColorRect = { x = 0, y = 84, width = 224, height = 170 },
				uvRect = { u0 = 0.233398, v0 = 0.563965, u1 = 0.342773, v1 = 0.646973 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hospital_bed_destroyed",
				spriteColorRect = { x = 0, y = 82, width = 224, height = 172 },
				uvRect = { u0 = 0.00195312, v0 = 0.480957, u1 = 0.111328, v1 = 0.564941 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hospital_bed_occupied",
				spriteColorRect = { x = 0, y = 84, width = 224, height = 170 },
				uvRect = { u0 = 0.242188, v0 = 0.479004, u1 = 0.351562, v1 = 0.562012 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hospital_bed_occupied_damaged",
				spriteColorRect = { x = 0, y = 84, width = 224, height = 170 },
				uvRect = { u0 = 0.00195312, v0 = 0.566895, u1 = 0.111328, v1 = 0.649902 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hydro_farm",
				spriteColorRect = { x = 14, y = 198, width = 100, height = 54 },
				uvRect = { u0 = 0.105469, v0 = 0.932129, u1 = 0.154297, v1 = 0.958496 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hydro_farm_destroyed",
				spriteColorRect = { x = 14, y = 199, width = 100, height = 54 },
				uvRect = { u0 = 0.0546875, v0 = 0.932129, u1 = 0.103516, v1 = 0.958496 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "o2_filtermachine",
				spriteColorRect = { x = 13, y = 2, width = 91, height = 136 },
				uvRect = { u0 = 0.801758, v0 = 0.76416, u1 = 0.868164, v1 = 0.808594 },
				spriteSourceSize = { width = 111, height = 152 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler",
				spriteColorRect = { x = 0, y = 16, width = 106, height = 150 },
				uvRect = { u0 = 0.516602, v0 = 0.648926, u1 = 0.589844, v1 = 0.700684 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler_damaged",
				spriteColorRect = { x = 0, y = 16, width = 106, height = 164 },
				uvRect = { u0 = 0.870117, v0 = 0.489746, u1 = 0.950195, v1 = 0.541504 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler_destroyed",
				spriteColorRect = { x = 0, y = 18, width = 108, height = 162 },
				uvRect = { u0 = 0.873047, v0 = 0.254395, u1 = 0.952148, v1 = 0.307129 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler_level2",
				spriteColorRect = { x = 0, y = 6, width = 220, height = 228 },
				uvRect = { u0 = 0.120117, v0 = 0.470215, u1 = 0.231445, v1 = 0.577637 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler_level2_damaged",
				spriteColorRect = { x = 0, y = 6, width = 228, height = 232 },
				uvRect = { u0 = 0.402344, v0 = 0.446777, u1 = 0.515625, v1 = 0.558105 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "oxygen_recycler_level2_destroyed",
				spriteColorRect = { x = 0, y = 8, width = 246, height = 230 },
				uvRect = { u0 = 0.00195312, v0 = 0.252441, u1 = 0.12207, v1 = 0.364746 },
				spriteSourceSize = { width = 256, height = 238 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_corn_01_a",
				spriteColorRect = { x = 109, y = 168, width = 44, height = 38 },
				uvRect = { u0 = 0.208008, v0 = 0.834473, u1 = 0.226562, v1 = 0.855957 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_corn_01_a_dead",
				spriteColorRect = { x = 109, y = 168, width = 44, height = 38 },
				uvRect = { u0 = 0.189453, v0 = 0.90625, u1 = 0.208008, v1 = 0.927734 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_corn_01_b",
				spriteColorRect = { x = 99, y = 79, width = 70, height = 142 },
				uvRect = { u0 = 0.480469, v0 = 0.581543, u1 = 0.514648, v1 = 0.650879 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_corn_01_b_dead",
				spriteColorRect = { x = 99, y = 79, width = 70, height = 142 },
				uvRect = { u0 = 0.833984, v0 = 0.474121, u1 = 0.868164, v1 = 0.543457 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_corn_01_c",
				spriteColorRect = { x = 68, y = 77, width = 126, height = 144 },
				uvRect = { u0 = 0.638672, v0 = 0.690918, u1 = 0.708984, v1 = 0.752441 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_corn_01_c_dead",
				spriteColorRect = { x = 68, y = 77, width = 126, height = 144 },
				uvRect = { u0 = 0.514648, v0 = 0.702637, u1 = 0.584961, v1 = 0.76416 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_glowfruit_01_a",
				spriteColorRect = { x = 94, y = 168, width = 70, height = 38 },
				uvRect = { u0 = 0.107422, v0 = 0.960449, u1 = 0.125977, v1 = 0.994629 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_glowfruit_01_a_dead",
				spriteColorRect = { x = 94, y = 169, width = 70, height = 42 },
				uvRect = { u0 = 0.778809, v0 = 0.825195, u1 = 0.799316, v1 = 0.859375 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_glowfruit_01_b",
				spriteColorRect = { x = 93, y = 140, width = 70, height = 66 },
				uvRect = { u0 = 0.604492, v0 = 0.553223, u1 = 0.636719, v1 = 0.587402 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_glowfruit_01_b_dead",
				spriteColorRect = { x = 88, y = 143, width = 82, height = 68 },
				uvRect = { u0 = 0.12793, v0 = 0.960449, u1 = 0.167969, v1 = 0.993652 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_glowfruit_01_c",
				spriteColorRect = { x = 69, y = 116, width = 112, height = 92 },
				uvRect = { u0 = 0.591797, v0 = 0.687988, u1 = 0.636719, v1 = 0.742676 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_glowfruit_01_c_dead",
				spriteColorRect = { x = 81, y = 129, width = 90, height = 82 },
				uvRect = { u0 = 0.0957031, v0 = 0.861328, u1 = 0.135742, v1 = 0.905273 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_pod_01_a",
				spriteColorRect = { x = 113, y = 168, width = 30, height = 36 },
				uvRect = { u0 = 0.782227, v0 = 0.740234, u1 = 0.799805, v1 = 0.754883 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_pod_01_a_dead",
				spriteColorRect = { x = 114, y = 167, width = 38, height = 38 },
				uvRect = { u0 = 0.245117, v0 = 0.834473, u1 = 0.263672, v1 = 0.853027 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_pod_01_b",
				spriteColorRect = { x = 69, y = 83, width = 140, height = 136 },
				uvRect = { u0 = 0.801758, v0 = 0.693848, u1 = 0.868164, v1 = 0.762207 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_pod_01_b_dead",
				spriteColorRect = { x = 69, y = 83, width = 140, height = 136 },
				uvRect = { u0 = 0.801758, v0 = 0.623535, u1 = 0.868164, v1 = 0.691895 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_pod_01_c",
				spriteColorRect = { x = 69, y = 139, width = 108, height = 80 },
				uvRect = { u0 = 0.0976562, v0 = 0.740723, u1 = 0.150391, v1 = 0.779785 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_pod_01_c_dead",
				spriteColorRect = { x = 70, y = 139, width = 108, height = 84 },
				uvRect = { u0 = 0.947754, v0 = 0.931641, u1 = 0.98877, v1 = 0.984375 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_xmas_a",
				spriteColorRect = { x = 110, y = 147, width = 42, height = 58 },
				uvRect = { u0 = 0.00195312, v0 = 0.90918, u1 = 0.0302734, v1 = 0.929688 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_xmas_a_dead",
				spriteColorRect = { x = 110, y = 149, width = 40, height = 56 },
				uvRect = { u0 = 0.780273, v0 = 0.772461, u1 = 0.799805, v1 = 0.799805 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_xmas_b",
				spriteColorRect = { x = 85, y = 88, width = 88, height = 122 },
				uvRect = { u0 = 0.00195312, v0 = 0.84668, u1 = 0.0449219, v1 = 0.90625 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_xmas_b_dead",
				spriteColorRect = { x = 81, y = 89, width = 100, height = 140 },
				uvRect = { u0 = 0.949219, v0 = 0.65625, u1 = 0.998047, v1 = 0.724609 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "plant_xmas_c",
				spriteColorRect = { x = 85, y = 88, width = 88, height = 122 },
				uvRect = { u0 = 0.862793, v0 = 0.887207, u1 = 0.922363, v1 = 0.930176 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "plant_xmas_c_dead",
				spriteColorRect = { x = 85, y = 89, width = 88, height = 140 },
				uvRect = { u0 = 0.709961, v0 = 0.759766, u1 = 0.77832, v1 = 0.802734 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "raider_spacebus",
				spriteColorRect = { x = 16, y = 22, width = 698, height = 373 },
				uvRect = { u0 = 0.40332, v0 = 0.00195312, u1 = 0.744141, v1 = 0.184082 },
				spriteSourceSize = { width = 736, height = 409 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "raider_spacebus_back",
				spriteColorRect = { x = 0, y = 0, width = 818, height = 509 },
				uvRect = { u0 = 0.00195312, v0 = 0.00195312, u1 = 0.401367, v1 = 0.250488 },
				spriteSourceSize = { width = 838, height = 509 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "reactor_console",
				spriteColorRect = { x = 1, y = 2, width = 104, height = 118 },
				uvRect = { u0 = 0.155273, v0 = 0.84668, u1 = 0.206055, v1 = 0.904297 },
				spriteSourceSize = { width = 126, height = 138 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "reactor_server_machine",
				spriteColorRect = { x = 7, y = 7, width = 98, height = 162 },
				uvRect = { u0 = 0.870117, v0 = 0.543457, u1 = 0.949219, v1 = 0.591309 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "reactor_tileguts",
				spriteColorRect = { x = 0, y = 0, width = 139, height = 82 },
				uvRect = { u0 = 0.708984, v0 = 0.804688, u1 = 0.776855, v1 = 0.844727 },
				spriteSourceSize = { width = 139, height = 86 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "refinery",
				spriteColorRect = { x = 68, y = 15, width = 146, height = 238 },
				uvRect = { u0 = 0.242188, v0 = 0.405762, u1 = 0.358398, v1 = 0.477051 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "refinery_damaged",
				spriteColorRect = { x = 68, y = 15, width = 146, height = 238 },
				uvRect = { u0 = 0.520996, v0 = 0.399902, u1 = 0.637207, v1 = 0.471191 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "refinery_destroyed",
				spriteColorRect = { x = 68, y = 15, width = 146, height = 238 },
				uvRect = { u0 = 0.402832, v0 = 0.373535, u1 = 0.519043, v1 = 0.444824 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "refinery_level2",
				spriteColorRect = { x = 62, y = 16, width = 152, height = 240 },
				uvRect = { u0 = 0.246094, v0 = 0.32959, u1 = 0.363281, v1 = 0.403809 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "refinery_level2_damaged",
				spriteColorRect = { x = 60, y = 17, width = 154, height = 240 },
				uvRect = { u0 = 0.40332, v0 = 0.296387, u1 = 0.520508, v1 = 0.371582 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "refinery_level2_destroyed",
				spriteColorRect = { x = 60, y = 16, width = 154, height = 240 },
				uvRect = { u0 = 0.246094, v0 = 0.252441, u1 = 0.363281, v1 = 0.327637 },
				spriteSourceSize = { width = 282, height = 282 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "research_desk",
				spriteColorRect = { x = 12, y = 120, width = 178, height = 160 },
				uvRect = { u0 = 0.638672, v0 = 0.489746, u1 = 0.725586, v1 = 0.567871 },
				spriteSourceSize = { width = 192, height = 280 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "research_desk_damaged",
				spriteColorRect = { x = 19, y = 121, width = 170, height = 158 },
				uvRect = { u0 = 0.638672, v0 = 0.569824, u1 = 0.72168, v1 = 0.646973 },
				spriteSourceSize = { width = 192, height = 280 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "research_desk_destroyed",
				spriteColorRect = { x = 19, y = 121, width = 170, height = 158 },
				uvRect = { u0 = 0.870117, v0 = 0.593262, u1 = 0.947266, v1 = 0.67627 },
				spriteSourceSize = { width = 192, height = 280 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "residence_dresser01",
				spriteColorRect = { x = 3, y = 139, width = 92, height = 100 },
				uvRect = { u0 = 0.948242, v0 = 0.884766, u1 = 0.99707, v1 = 0.929688 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "residence_houseplant",
				spriteColorRect = { x = 22, y = 129, width = 82, height = 108 },
				uvRect = { u0 = 0.0429688, v0 = 0.726074, u1 = 0.0957031, v1 = 0.766113 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "residence_rug01",
				spriteColorRect = { x = 0, y = 22, width = 138, height = 73 },
				uvRect = { u0 = 0.365234, v0 = 0.312988, u1 = 0.400879, v1 = 0.380371 },
				spriteSourceSize = { width = 168, height = 95 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "rifle_rack",
				spriteColorRect = { x = 41, y = 114, width = 82, height = 126 },
				uvRect = { u0 = 0.801758, v0 = 0.810547, u1 = 0.863281, v1 = 0.850586 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "seedpod01",
				spriteColorRect = { x = 0, y = 0, width = 246, height = 256 },
				uvRect = { u0 = 0.746094, v0 = 0.162598, u1 = 0.871094, v1 = 0.282715 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "spacebus",
				spriteColorRect = { x = 17, y = 1, width = 422, height = 325 },
				uvRect = { u0 = 0.746094, v0 = 0.00195312, u1 = 0.952148, v1 = 0.160645 },
				spriteSourceSize = { width = 440, height = 335 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "spawner",
				spriteColorRect = { x = 27, y = 12, width = 76, height = 48 },
				uvRect = { u0 = 0.0566406, v0 = 0.960449, u1 = 0.0800781, v1 = 0.997559 },
				spriteSourceSize = { width = 128, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "spawner_flipY",
				spriteColorRect = { x = 27, y = 5, width = 76, height = 48 },
				uvRect = { u0 = 0.03125, v0 = 0.960449, u1 = 0.0546875, v1 = 0.997559 },
				spriteSourceSize = { width = 128, height = 64 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "standing_table",
				spriteColorRect = { x = 36, y = 153, width = 56, height = 84 },
				uvRect = { u0 = 0.15625, v0 = 0.930664, u1 = 0.197266, v1 = 0.958008 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "stove",
				spriteColorRect = { x = 23, y = 143, width = 88, height = 106 },
				uvRect = { u0 = 0.208008, v0 = 0.861328, u1 = 0.259766, v1 = 0.904297 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "stove_damaged",
				spriteColorRect = { x = 20, y = 153, width = 92, height = 96 },
				uvRect = { u0 = 0.046875, v0 = 0.861328, u1 = 0.09375, v1 = 0.90625 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "stove_destroyed",
				spriteColorRect = { x = 20, y = 99, width = 88, height = 150 },
				uvRect = { u0 = 0.59375, v0 = 0.612793, u1 = 0.636719, v1 = 0.686035 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turf",
				spriteColorRect = { x = 0, y = 186, width = 128, height = 70 },
				uvRect = { u0 = 0.478516, v0 = 0.652832, u1 = 0.512695, v1 = 0.715332 },
				spriteSourceSize = { width = 128, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_destroyed",
				spriteColorRect = { x = 19, y = 71, width = 198, height = 148 },
				uvRect = { u0 = 0.744141, v0 = 0.391113, u1 = 0.84082, v1 = 0.463379 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_destroyed_flipY",
				spriteColorRect = { x = 100, y = 101, width = 126, height = 90 },
				uvRect = { u0 = 0.954102, v0 = 0.154297, u1 = 0.998047, v1 = 0.21582 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_frames0001",
				spriteColorRect = { x = 39, y = 68, width = 214, height = 154 },
				uvRect = { u0 = 0.113281, v0 = 0.57959, u1 = 0.217773, v1 = 0.654785 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_frames0001_flipY",
				spriteColorRect = { x = 100, y = 101, width = 152, height = 90 },
				uvRect = { u0 = 0.954102, v0 = 0.078125, u1 = 0.998047, v1 = 0.152344 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_frames0002",
				spriteColorRect = { x = 33, y = 72, width = 208, height = 148 },
				uvRect = { u0 = 0.640625, v0 = 0.340332, u1 = 0.742188, v1 = 0.412598 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_frames0002_flipY",
				spriteColorRect = { x = 100, y = 101, width = 152, height = 90 },
				uvRect = { u0 = 0.954102, v0 = 0.00195312, u1 = 0.998047, v1 = 0.0761719 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_frames0003",
				spriteColorRect = { x = 19, y = 71, width = 202, height = 148 },
				uvRect = { u0 = 0.00195312, v0 = 0.651855, u1 = 0.100586, v1 = 0.724121 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_frames0003_flipY",
				spriteColorRect = { x = 100, y = 99, width = 132, height = 92 },
				uvRect = { u0 = 0.953125, v0 = 0.398438, u1 = 0.998047, v1 = 0.462891 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_frames0004",
				spriteColorRect = { x = 8, y = 71, width = 196, height = 150 },
				uvRect = { u0 = 0.63916, v0 = 0.414551, u1 = 0.734863, v1 = 0.487793 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_frames0004_flipY",
				spriteColorRect = { x = 99, y = 85, width = 70, height = 106 },
				uvRect = { u0 = 0.101562, v0 = 0.794922, u1 = 0.15332, v1 = 0.829102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_frames0005",
				spriteColorRect = { x = 1, y = 72, width = 194, height = 150 },
				uvRect = { u0 = 0.517578, v0 = 0.473145, u1 = 0.612305, v1 = 0.546387 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_frames0005_flipY",
				spriteColorRect = { x = 85, y = 85, width = 84, height = 106 },
				uvRect = { u0 = 0.102539, v0 = 0.687012, u1 = 0.143555, v1 = 0.73877 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_destroyed",
				spriteColorRect = { x = 75, y = 101, width = 100, height = 86 },
				uvRect = { u0 = 0.00195312, v0 = 0.794922, u1 = 0.0439453, v1 = 0.84375 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_lv2_destroyed_flipY",
				spriteColorRect = { x = 103, y = 94, width = 124, height = 98 },
				uvRect = { u0 = 0.865234, v0 = 0.837402, u1 = 0.925781, v1 = 0.885254 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0001",
				spriteColorRect = { x = 75, y = 102, width = 140, height = 78 },
				uvRect = { u0 = 0.638672, v0 = 0.794434, u1 = 0.707031, v1 = 0.83252 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0001_flipY",
				spriteColorRect = { x = 104, y = 109, width = 148, height = 82 },
				uvRect = { u0 = 0.638672, v0 = 0.648926, u1 = 0.710938, v1 = 0.688965 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0002",
				spriteColorRect = { x = 75, y = 102, width = 142, height = 78 },
				uvRect = { u0 = 0.638672, v0 = 0.754395, u1 = 0.708008, v1 = 0.79248 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0002_flipY",
				spriteColorRect = { x = 104, y = 109, width = 150, height = 82 },
				uvRect = { u0 = 0.360352, v0 = 0.435059, u1 = 0.400391, v1 = 0.508301 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_lv2_frames0003",
				spriteColorRect = { x = 74, y = 102, width = 118, height = 90 },
				uvRect = { u0 = 0.954102, v0 = 0.217773, u1 = 0.998047, v1 = 0.275391 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_lv2_frames0003_flipY",
				spriteColorRect = { x = 103, y = 93, width = 126, height = 98 },
				uvRect = { u0 = 0.870117, v0 = 0.787598, u1 = 0.931641, v1 = 0.835449 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0004",
				spriteColorRect = { x = 69, y = 102, width = 60, height = 104 },
				uvRect = { u0 = 0.155273, v0 = 0.656738, u1 = 0.206055, v1 = 0.686035 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_lv2_frames0004_flipY",
				spriteColorRect = { x = 104, y = 79, width = 62, height = 112 },
				uvRect = { u0 = 0.155273, v0 = 0.794922, u1 = 0.209961, v1 = 0.825195 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "turret_lv2_frames0005",
				spriteColorRect = { x = 53, y = 101, width = 72, height = 104 },
				uvRect = { u0 = 0.365234, v0 = 0.382324, u1 = 0.400391, v1 = 0.433105 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "turret_lv2_frames0005_flipY",
				spriteColorRect = { x = 90, y = 81, width = 70, height = 110 },
				uvRect = { u0 = 0.0458984, v0 = 0.794922, u1 = 0.0996094, v1 = 0.829102 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "tv_screen01",
				spriteColorRect = { x = 0, y = 9, width = 84, height = 90 },
				uvRect = { u0 = 0.954102, v0 = 0.277344, u1 = 0.998047, v1 = 0.318359 },
				spriteSourceSize = { width = 138, height = 190 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "weightbench",
				spriteColorRect = { x = 22, y = 1, width = 196, height = 182 },
				uvRect = { u0 = 0.654297, v0 = 0.186035, u1 = 0.743164, v1 = 0.281738 },
				spriteSourceSize = { width = 218, height = 192 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "weightbench_inuse",
				spriteColorRect = { x = 21, y = 21, width = 184, height = 162 },
				uvRect = { u0 = 0.873047, v0 = 0.162598, u1 = 0.952148, v1 = 0.252441 },
				spriteSourceSize = { width = 218, height = 192 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

