-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:4cf9ee9f7c6cd7a6cda88d0601ab9120:113b2119d52cde47acf834fbc12967e0:f106f5937eb9e44828d6b746f28aebb3$
-- 

return {
	texture = 'Test.png',
	frames = {
			{
				name = "TestObject",
				spriteColorRect = { x = 0, y = 0, width = 124, height = 180 },
				uvRect = { u0 = 0.0078125, v0 = 0.015625, u1 = 0.25, v1 = 0.71875 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "TestObject_damaged",
				spriteColorRect = { x = 0, y = 0, width = 124, height = 180 },
				uvRect = { u0 = 0.257812, v0 = 0.015625, u1 = 0.5, v1 = 0.71875 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "TestObject_destroyed",
				spriteColorRect = { x = 0, y = 0, width = 124, height = 180 },
				uvRect = { u0 = 0.507812, v0 = 0.015625, u1 = 0.75, v1 = 0.71875 },
				spriteSourceSize = { width = 124, height = 180 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

