-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:38ec4a1c4ba96424ad478d5afb1144b0$
-- 

return {
	texture = 'Inspector.tex',
	frames = {
			{
				name = "ui_icon_about.png",
				spriteColorRect = { x = 6, y = 0, width = 16, height = 28 },
				uvRect = { u0 = 0.886719, v0 = 0.230469, u1 = 0.917969, v1 = 0.285156 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_activity.png",
				spriteColorRect = { x = 0, y = 6, width = 28, height = 16 },
				uvRect = { u0 = 0.832031, v0 = 0.0820312, u1 = 0.886719, v1 = 0.113281 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_band.png",
				spriteColorRect = { x = 2, y = 2, width = 20, height = 22 },
				uvRect = { u0 = 0.953125, v0 = 0.121094, u1 = 0.992188, v1 = 0.164062 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_bulletpoint.png",
				spriteColorRect = { x = 6, y = 6, width = 14, height = 14 },
				uvRect = { u0 = 0.871094, v0 = 0.292969, u1 = 0.898438, v1 = 0.320312 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_duty.png",
				spriteColorRect = { x = 0, y = 6, width = 28, height = 16 },
				uvRect = { u0 = 0.832031, v0 = 0.0820312, u1 = 0.886719, v1 = 0.113281 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_enemy.png",
				spriteColorRect = { x = 6, y = 2, width = 16, height = 24 },
				uvRect = { u0 = 0.421875, v0 = 0.546875, u1 = 0.453125, v1 = 0.59375 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_food.png",
				spriteColorRect = { x = 4, y = 2, width = 18, height = 22 },
				uvRect = { u0 = 0.941406, v0 = 0.210938, u1 = 0.976562, v1 = 0.253906 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_friend.png",
				spriteColorRect = { x = 6, y = 0, width = 16, height = 26 },
				uvRect = { u0 = 0.832031, v0 = 0.269531, u1 = 0.863281, v1 = 0.320312 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_health.png",
				spriteColorRect = { x = 4, y = 6, width = 20, height = 16 },
				uvRect = { u0 = 0.941406, v0 = 0.171875, u1 = 0.980469, v1 = 0.203125 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_location.png",
				spriteColorRect = { x = 0, y = 6, width = 28, height = 14 },
				uvRect = { u0 = 0.832031, v0 = 0.121094, u1 = 0.886719, v1 = 0.148438 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_morale.png",
				spriteColorRect = { x = 6, y = 6, width = 16, height = 16 },
				uvRect = { u0 = 0.460938, v0 = 0.546875, u1 = 0.492188, v1 = 0.578125 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_needs.png",
				spriteColorRect = { x = 6, y = 2, width = 16, height = 24 },
				uvRect = { u0 = 0.382812, v0 = 0.546875, u1 = 0.414062, v1 = 0.59375 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_psych.png",
				spriteColorRect = { x = 2, y = 4, width = 24, height = 22 },
				uvRect = { u0 = 0.832031, v0 = 0.21875, u1 = 0.878906, v1 = 0.261719 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_research.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 26 },
				uvRect = { u0 = 0.886719, v0 = 0.171875, u1 = 0.933594, v1 = 0.222656 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_room_satisfaction.png",
				spriteColorRect = { x = 0, y = 2, width = 28, height = 22 },
				uvRect = { u0 = 0.90625, v0 = 0.0703125, u1 = 0.960938, v1 = 0.113281 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_self_esteem.png",
				spriteColorRect = { x = 6, y = 2, width = 16, height = 24 },
				uvRect = { u0 = 0.925781, v0 = 0.261719, u1 = 0.957031, v1 = 0.308594 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_spaceface.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 28 },
				uvRect = { u0 = 0.90625, v0 = 0.0078125, u1 = 0.960938, v1 = 0.0625 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_icon_stats.png",
				spriteColorRect = { x = 0, y = 2, width = 26, height = 22 },
				uvRect = { u0 = 0.894531, v0 = 0.121094, u1 = 0.945312, v1 = 0.164062 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_icon_zoning.png",
				spriteColorRect = { x = 2, y = 0, width = 24, height = 28 },
				uvRect = { u0 = 0.832031, v0 = 0.15625, u1 = 0.878906, v1 = 0.210938 },
				spriteSourceSize = { width = 28, height = 28 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_buttonEdit.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 34 },
				uvRect = { u0 = 0.832031, v0 = 0.0078125, u1 = 0.898438, v1 = 0.0742188 },
				spriteSourceSize = { width = 33, height = 33 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_dutybutton.png",
				spriteColorRect = { x = 0, y = 0, width = 404, height = 62 },
				uvRect = { u0 = 0.0078125, v0 = 0.289062, u1 = 0.796875, v1 = 0.410156 },
				spriteSourceSize = { width = 403, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_dutybuttonlabel.png",
				spriteColorRect = { x = 0, y = 0, width = 188, height = 58 },
				uvRect = { u0 = 0.0078125, v0 = 0.546875, u1 = 0.375, v1 = 0.660156 },
				spriteSourceSize = { width = 187, height = 58 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderActive.png",
				spriteColorRect = { x = 0, y = 0, width = 418, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.199219, u1 = 0.824219, v1 = 0.28125 },
				spriteSourceSize = { width = 418, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderActive_5wide.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.757812, u1 = 0.171875, v1 = 0.839844 },
				spriteSourceSize = { width = 83, height = 42 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderInactive.png",
				spriteColorRect = { x = 0, y = 0, width = 418, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.109375, u1 = 0.824219, v1 = 0.191406 },
				spriteSourceSize = { width = 418, height = 42 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderInactive_5wide.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 42 },
				uvRect = { u0 = 0.0078125, v0 = 0.667969, u1 = 0.171875, v1 = 0.75 },
				spriteSourceSize = { width = 83, height = 42 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderTop.png",
				spriteColorRect = { x = 0, y = 0, width = 418, height = 48 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.824219, v1 = 0.101562 },
				spriteSourceSize = { width = 418, height = 47 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_folderTop_5wide.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 48 },
				uvRect = { u0 = 0.804688, v0 = 0.328125, u1 = 0.96875, v1 = 0.421875 },
				spriteSourceSize = { width = 83, height = 47 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_rezoneActive.png",
				spriteColorRect = { x = 0, y = 0, width = 248, height = 62 },
				uvRect = { u0 = 0.5, v0 = 0.429688, u1 = 0.984375, v1 = 0.550781 },
				spriteSourceSize = { width = 247, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "ui_inspector_rezoneInactive.png",
				spriteColorRect = { x = 0, y = 0, width = 248, height = 62 },
				uvRect = { u0 = 0.0078125, v0 = 0.417969, u1 = 0.492188, v1 = 0.539062 },
				spriteSourceSize = { width = 247, height = 62 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

