-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:6b8c8322cf1e2480487494b2b148facd:cdb04a9d750de63d0186a27cf9251298:b00d91984dea6c339081e8edf6524b6e$
-- 

return {
	texture = 'TestStuff.png',
	frames = {
			{
				name = "Stuff_LargeCup",
				spriteColorRect = { x = 0, y = 0, width = 256, height = 256 },
				uvRect = { u0 = 0.0078125, v0 = 0.0078125, u1 = 0.507812, v1 = 0.507812 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

