local Gui = require('UI.Gui')

local nButtonWidth, nButtonHeight  = 400, 64 -- 330, 81
local nTextHeight = nButtonHeight
local nButtonStartY = -134
local nIconX, nIconStartY = 10, -136
local nDoneIconStartY = -2
local nLabelX, nLabelStartY = 30, -138 -- 94, -144
local nLabelNoIconX, nLabelButtonStartY = 10, -10
local nDoneLabelStartY = -10
local nHotkeyX, nHotkeyStartY = -75, -155 -- nButtonWidth - 112, -180
local nDoneHotkeyY = -46
local nIconScale = .6
local numButtons = 15
local nBGWidth = 160

return
{
    posInfo =
        {
        alignX = 'left',
        alignY = 'top',
        offsetX = 0,
        offsetY = 0,
        scale = { 1, 1 },
    },
    tElements =
    {
        {
            key = 'LargeBar',
            type = 'onePixel',
            pos = { 0, 0 },
            scale = { nButtonWidth, -nButtonStartY + (nButtonHeight * numButtons) },
            color = Gui.SIDEBAR_BG,
        },
        {
            key = 'DoneButton',
            type = 'onePixelButton',
            pos = { 0, 0 },
            scale = { nButtonWidth, nButtonHeight + 10 },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'DoneButton', color = Gui.AMBER, },
                { key = 'DoneLabel', color = Gui.BLACK, },
                { key = 'DoneHotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'DoneButton', color = Gui.BLACK, },
                { key = 'DoneLabel', color = Gui.AMBER, },
                { key = 'DoneHotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot1Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot1Button', color = Gui.AMBER, },
                { key = 'Slot1Label', color = Gui.BLACK, },
                { key = 'Slot1Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot1Button', color = Gui.BLACK, },
                { key = 'Slot1Label', color = Gui.AMBER, },
                { key = 'Slot1Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot1Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY },
            text = 'Test 1',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot1Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY },
            text = '1.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot2Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 1 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot2Button', color = Gui.AMBER, },
                { key = 'Slot2Label', color = Gui.BLACK, },
                { key = 'Slot2Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot2Button', color = Gui.BLACK, },
                { key = 'Slot2Label', color = Gui.AMBER, },
                { key = 'Slot2Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot2Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 1 },
            text = 'Test 2',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot2Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 1 },
            text = '2.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot3Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 2 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot3Button', color = Gui.AMBER, },
                { key = 'Slot3Label', color = Gui.BLACK, },
                { key = 'Slot3Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot3Button', color = Gui.BLACK, },
                { key = 'Slot3Label', color = Gui.AMBER, },
                { key = 'Slot3Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot3Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 2 },
            text = 'Test 3',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot3Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 2 },
            text = '3.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot4Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 3 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot4Button', color = Gui.AMBER, },
                { key = 'Slot4Label', color = Gui.BLACK, },
                { key = 'Slot4Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot4Button', color = Gui.BLACK, },
                { key = 'Slot4Label', color = Gui.AMBER, },
                { key = 'Slot4Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot4Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 3 },
            text = 'Test 4',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot4Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 3 },
            text = '4.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot5Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 4 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot5Button', color = Gui.AMBER, },
                { key = 'Slot5Label', color = Gui.BLACK, },
                { key = 'Slot5Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot5Button', color = Gui.BLACK, },
                { key = 'Slot5Label', color = Gui.AMBER, },
                { key = 'Slot5Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot5Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 4 },
            text = 'Test 5',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot5Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 4 },
            text = '5.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot6Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 5 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot6Button', color = Gui.AMBER, },
                { key = 'Slot6Label', color = Gui.BLACK, },
                { key = 'Slot6Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot6Button', color = Gui.BLACK, },
                { key = 'Slot6Label', color = Gui.AMBER, },
                { key = 'Slot6Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot6Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 5 },
            text = 'Test 6',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot6Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 5 },
            text = '6.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot7Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 6 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot7Button', color = Gui.AMBER, },
                { key = 'Slot7Label', color = Gui.BLACK, },
                { key = 'Slot7Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot7Button', color = Gui.BLACK, },
                { key = 'Slot7Label', color = Gui.AMBER, },
                { key = 'Slot7Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot7Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 6 },
            text = 'Test 7',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot7Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 6 },
            text = '7.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot8Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 7 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot8Button', color = Gui.AMBER, },
                { key = 'Slot8Label', color = Gui.BLACK, },
                { key = 'Slot8Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot8Button', color = Gui.BLACK, },
                { key = 'Slot8Label', color = Gui.AMBER, },
                { key = 'Slot8Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot8Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 7 },
            text = 'Test 8',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot8Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 7 },
            text = '8.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot9Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 8 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot9Button', color = Gui.AMBER, },
                { key = 'Slot9Label', color = Gui.BLACK, },
                { key = 'Slot9Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot9Button', color = Gui.BLACK, },
                { key = 'Slot9Label', color = Gui.AMBER, },
                { key = 'Slot9Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot9Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 8 },
            text = 'Test 9',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot9Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 8 },
            text = '9.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot10Button',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 9 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'Slot10Button', color = Gui.AMBER, },
                { key = 'Slot10Label', color = Gui.BLACK, },
                { key = 'ClearBeaconIcon', color = Gui.BLACK, },
                { key = 'Slot10Hotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'Slot10Button', color = Gui.BLACK, },
                { key = 'Slot10Label', color = Gui.AMBER, },
                { key = 'ClearBeaconIcon', color = Gui.AMBER, },
                { key = 'Slot10Hotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'Slot10Label',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 9 },
            text = 'Test 10',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'Slot10Hotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 9 },
            text = '0.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatHighButton',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 10 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'ThreatHighButton', color = Gui.AMBER, },
                { key = 'ThreatHighLabel', color = Gui.BLACK, },
                { key = 'ThreatHighHotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'ThreatHighButton', color = Gui.BLACK, },
                { key = 'ThreatHighLabel', color = Gui.AMBER, },
                { key = 'ThreatHighHotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'ThreatHighLabel',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 10 },
            linecode = 'SQUAD021TEXT',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatHighHotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 10 },
            text = 'z.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatMediumButton',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 11 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'ThreatMediumButton', color = Gui.AMBER, },
                { key = 'ThreatMediumLabel', color = Gui.BLACK, },
                { key = 'ThreatMediumHotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'ThreatMediumButton', color = Gui.BLACK, },
                { key = 'ThreatMediumLabel', color = Gui.AMBER, },
                { key = 'ThreatMediumHotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'ThreatMediumLabel',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 11 },
            linecode = 'SQUAD022TEXT',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatMediumHotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 11 },
            text = 'x.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatLowButton',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 12 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'ThreatLowButton', color = Gui.AMBER, },
                { key = 'ThreatLowLabel', color = Gui.BLACK, },
                { key = 'ThreatLowHotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'ThreatLowButton', color = Gui.BLACK, },
                { key = 'ThreatLowLabel', color = Gui.AMBER, },
                { key = 'ThreatLowHotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'ThreatLowLabel',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 12 },
            linecode = 'SQUAD023TEXT',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'ThreatLowHotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 12 },
            text = 'c.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'StandDownButton',
            type = 'onePixelButton',
            pos = { 0, nButtonStartY - nButtonHeight * 13 },
            scale = { nButtonWidth, nButtonHeight },
            color = Gui.BLACK,
            onHoverOn =
            {
                { key = 'StandDownButton', color = Gui.AMBER, },
                { key = 'StandDownLabel', color = Gui.BLACK, },
                { key = 'StandDownHotkey', color = Gui.BLACK, },
                { playSfx = 'hilight', },
            },
            onHoverOff =
            {
                { key = 'StandDownButton', color = Gui.BLACK, },
                { key = 'StandDownLabel', color = Gui.AMBER, },
                { key = 'StandDownHotkey', color = Gui.AMBER, },
            },
        },
		{
            key = 'StandDownLabel',
            type = 'textBox',
            pos = { nLabelX, nLabelStartY - nButtonHeight * 13 },
            linecode = 'SQUAD024TEXT',
            style = 'dosisregular40',
            rect = { 0, 300, 280, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
		{
            key = 'StandDownHotkey',
            type = 'textBox',
            pos = { nHotkeyX, nHotkeyStartY - nButtonHeight * 13 },
            text = 'v.',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
        {
            key = 'MenuSublabel',
            type = 'textBox',
            pos = { 40, -90 },
            linecode = "HUDHUD036TEXT",
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.LEFT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.GREY,
        },
        {
            key = 'DoneLabel',
            type = 'textBox',
            pos = { nLabelX, nDoneLabelStartY },
            linecode = 'HUDHUD035TEXT',
            style = 'dosisregular40',
            rect = { 0, 400, 200, 0 },
            hAlign = MOAITextBox.CENTER_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
        {
            key = 'DoneHotkey',
            type = 'textBox',
            pos = { nHotkeyX + 20, nDoneHotkeyY + 10 },
            text = 'ESC',
            style = 'dosissemibold22',
            rect = { 0, 100, 100, 0 },
            hAlign = MOAITextBox.RIGHT_JUSTIFY,
            vAlign = MOAITextBox.LEFT_JUSTIFY,
            color = Gui.AMBER,
        },
        {
            key = 'SidebarBottomEndcapExpanded',
            type = 'uiTexture',
            textureName = 'ui_hud_anglebottom',
            sSpritesheetPath = 'UI/HUD',
            pos = { 0, nButtonStartY - numButtons * nButtonHeight },
            scale = { 1.28, 1.28 },
            color = Gui.SIDEBAR_BG,
        },
    },
}
